# fly.toml app configuration file generated for part3phonebook-doubty on 2023-12-21T06:43:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "part3phonebook-doubty"
primary_region = "dfw"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
