POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Brennan Allen",
   "number": "12345567"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "number": "2340985643"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Brennan"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Dan Abramov",
   "number": "08-43987621"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Bo",
   "number": "09"
}

###
PUT http://localhost:3001/api/persons/6584eccb1339a24e598f0fb6
Content-Type: application/json

{
   "name": "Brennan Allen",
   "number": "10-233445-5"
}